name: ğŸš€ Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step to checkout the repository code
      - name: ğŸšš Checkout code
        uses: actions/checkout@v4

      # Step to install dependencies for the server (backend)
      - name: ğŸ“¦ Install backend dependencies
        working-directory: ./server  # Specify the server directory
        run: npm install

      # Step to build the server
      - name: ğŸ—ï¸ Build server
        working-directory: ./server  # Specify the server directory
        run: npm run build  # Replace with your build script if applicable

       # Replace with your start script if applicable

      # Step to set up environment variables for the server
      - name: Set up environment variables
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PORT: ${{ secrets.PORT }}
        run: echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> ./server/.env \
             && echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> ./server/.env \
             && echo "PORT=${{ secrets.PORT }}" >> ./server/.env

      # Step to run the server
      - name: ğŸ—ï¸ Run Server
        working-directory: ./server  
        run: npm run start  

      # Step to deploy the server to FTP
      - name: ğŸš€ Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.host }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          local-dir: ./server/build/  # Directory to upload to the FTP server
          server-dir: /uninews/  # Path on the FTP server
      